import React from "react";
export default data =results[
    
    {"category":"Science: Computers",
    "type":"multiple",
    "difficulty":"medium",
    "question":"Which of the following languages is used as a scripting language in the Unity 3D game engine?",
    "correct_answer":"C#",
    "incorrect_answers":["Java",
    "C++",
    "Objective-C"]},

    {"category":"Entertainment: Video Games",
    "type":"multiple",
    "difficulty":"easy",
    "question":"What was the original name of Crash Bandicoot?",
    "correct_answer":"Willie Wombat",
    "incorrect_answers":["Coco Bandicoot",
    "Marvelous Mole",
    "Wally Wombat"]},

    {"category":"Entertainment: Books",
    "type":"multiple",
    "difficulty":"hard",
    "question":"The novel &quot;Jane Eyre&quot; was written by what author? ",
    "correct_answer":"Charlotte Bront&euml;",
    "incorrect_answers":["Emily Bront&euml;",
    "Jane Austen",
    "Louisa May Alcott"]},

    {"category":"Geography",
    "type":"multiple",
    "difficulty":"hard",
    "question":"The Hunua Ranges is located in...",
    "correct_answer":"New Zealand",
    "incorrect_answers":["Nepal",
    "China",
    "Mexico"]},

    {"category":"Animals",
    "type":"boolean",
    "difficulty":"medium",
    "question":"Finnish Lapphund dogs were used for herding reindeer.",
    "correct_answer":"True",
    "incorrect_answers":["False"]},

    {"category":"Entertainment: Comics",
    "type":"multiple",
    "difficulty":"medium",
    "question":"In Calvin and Hobbes what is the name of Susie;s stuffed rabbit?",
    "correct_answer":"Mr. Bun",
    "incorrect_answers":["Mr. Bunbun",
    "Mr. Rabbit",
    "Mr. Hoppy"]},

    {"category":"General Knowledge",
    "type":"multiple",
    "difficulty":"easy",
    "question":"What are Panama hats made out of?",
    "correct_answer":"Straw",
    "incorrect_answers":["Silk",
    "Hemp",
    "Flax"]},

    {"category":"Science & Nature",
    "type":"multiple",
    "difficulty":"hard",
    "question":"In physics conservation of energy and conservation of momentum are both consequences of which of the following?",
    "correct_answer":"Noether&#039;s Theorem",
    "incorrect_answers":["Bell&#039;s Theorem",
    "Wick&#039;s Theorem",
    "Carnot&#039;s Theorem"]},

    {"category":"Entertainment: Comics",
    "type":"multiple",
    "difficulty":"medium",
    "question":"In the Hellboy universe who founded the BPRD?",
    "correct_answer":"Trevor Bruttenholm",
    "incorrect_answers":["Kate Corrigan",
    "Johann Kraus",
    "Benjamin Daimio"]},

    {"category":"General Knowledge",
    "type":"multiple",
    "difficulty":"medium",
    "question":"What are the three starter Pokemon available in Pokemon Black and White?",
    "correct_answer":"Snivy, Tepig, Oshawott",
    "incorrect_answers":["Snivy,Fennekin,  Froakie",
    "Chespin,Tepig,Froakie",
    "Chespin,Fennekin, Oshawott"]}]